(function () {
    'use strict';

    angular
        .module('services')
        .factory('analysisService', analysisService);

    analysisService.$inject = ['$http', 'logger'];

    function analysisService($http, logger) {
        var baseUrl = 'http://api.bosonnlp.com/tag/analysis';

        var service = {
            requestAnalysis: requestAnalysis,
            requestAnalysisUseAjax: requestAnalysisUseAjax,
            mockRequestAnalysis: mockRequestAnalysis
        };

        return service;

        function requestAnalysis(text) {
            return $http({
                method: 'POST',
                url: baseUrl,
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    'X-Token': 'x1qhvxzi.2840.A2FFGgTwOPil'
                },
                data: JSON.stringify(text)
            }).then(function (data) {
                return data;
            });
        }

        function requestAnalysisUseAjax(text, cb) {
            $.ajax({
                type: 'POST',
                url: baseUrl,
                data: JSON.stringify(text),
                //headers: {
                //    'Content-Type': 'application/json',
                //    'Accept': 'application/json',
                //    'X-Token': 'x1qhvxzi.2840.A2FFGgTwOPil'
                //},
                beforeSend: function (request) {
                    request.setRequestHeader('Accept', 'applicaton/json');
                    request.setRequestHeader('Content-Type', 'applicaton/json');
                    request.setRequestHeader('X-Token', 'x1qhvxzi.2840.A2FFGgTwOPil');
                },
                success: function(data) {
                    return cb(null, data);
                },
                error: function(e) {
                    return cb("请求分析出错!");
                }
            });
        }

        function mockRequestAnalysis() {
            var mockData = [
                    {
                        "tag": [
                            "NT",
                            "PU",
                            "VV",
                            "NN",
                            "DEC",
                            "NN",
                            "PU",
                            "NN",
                            "NN",
                            "PU",
                            "P",
                            "NR",
                            "VV",
                            "AS",
                            "NN",
                            "NN",
                            "PU",
                            "NN",
                            "NR",
                            "CC",
                            "NN",
                            "NR",
                            "CC",
                            "NR",
                            "PU",
                            "NR",
                            "ETC",
                            "NN",
                            "NN",
                            "AD",
                            "VV",
                            "PU",
                            "AD",
                            "PU",
                            "NN",
                            "VV",
                            "AD",
                            "P",
                            "NT",
                            "NT",
                            "VV",
                            "PU",
                            "DT",
                            "NN",
                            "VV",
                            "AS",
                            "PU",
                            "NR",
                            "CD",
                            "JJ",
                            "NN",
                            "PU",
                            "DEG",
                            "CD",
                            "DEG",
                            "NR",
                            "VA",
                            "CC",
                            "NN",
                            "DEC",
                            "NN",
                            "PU",
                            "P",
                            "PN",
                            "CC",
                            "NN",
                            "PU",
                            "NR",
                            "PU",
                            "NN",
                            "PU",
                            "NR",
                            "CD",
                            "NN",
                            "DEG",
                            "NN",
                            "NN",
                            "PU",
                            "P",
                            "NR",
                            "PU",
                            "NR",
                            "ETC",
                            "NN",
                            "AD",
                            "VV",
                            "VV",
                            "NN",
                            "CD",
                            "NN",
                            "DEG",
                            "JJ",
                            "NN",
                            "PU",
                            "NN",
                            "NN",
                            "PU",
                            "VV",
                            "NN",
                            "DEC",
                            "JJ",
                            "NN",
                            "PU",
                            "PU",
                            "LC",
                            "VV",
                            "PU",
                            "NN",
                            "NN",
                            "PU",
                            "PU",
                            "PN",
                            "VV",
                            "NR",
                            "VV",
                            "NN",
                            "LC",
                            "DEG",
                            "CD",
                            "M",
                            "NN",
                            "PU",
                            "PU",
                            "PN",
                            "AD",
                            "AD",
                            "VC",
                            "PN",
                            "DEG",
                            "NN",
                            "NN",
                            "SP",
                            "PU",
                            "PU"
                        ],
                        "word": [
                            "15日",
                            "，",
                            "备受",
                            "关注",
                            "的",
                            "电影",
                            "《",
                            "黄金",
                            "时代",
                            "》",
                            "在",
                            "北京",
                            "举行",
                            "了",
                            "电影",
                            "发布会",
                            "，",
                            "导演",
                            "许鞍华",
                            "和",
                            "编剧",
                            "李樯",
                            "及",
                            "汤唯",
                            "、",
                            "冯绍峰",
                            "等",
                            "众",
                            "星",
                            "悉数",
                            "亮相",
                            "。",
                            "据悉",
                            "，",
                            "电影",
                            "确定",
                            "将",
                            "于",
                            "10月",
                            "1日",
                            "公映",
                            "。",
                            "本",
                            "片",
                            "讲述",
                            "了",
                            "“",
                            "民国",
                            "四",
                            "大",
                            "才女",
                            "”",
                            "之",
                            "一",
                            "的",
                            "萧红",
                            "短暂",
                            "而",
                            "传奇",
                            "的",
                            "一生",
                            "，",
                            "通过",
                            "她",
                            "与",
                            "萧军",
                            "、",
                            "汪恩甲",
                            "、",
                            "端木蕻良",
                            "、",
                            "洛宾基",
                            "四",
                            "人",
                            "的",
                            "情感",
                            "纠葛",
                            "，",
                            "与",
                            "鲁迅",
                            "、",
                            "丁玲",
                            "等",
                            "人",
                            "一起",
                            "再现",
                            "上",
                            "世纪",
                            "30",
                            "年代",
                            "的",
                            "独特",
                            "风貌",
                            "。",
                            "电影",
                            "原名",
                            "《",
                            "穿过",
                            "爱情",
                            "的",
                            "漫长",
                            "旅程",
                            "》",
                            "，",
                            "后",
                            "更名",
                            "《",
                            "黄金",
                            "时代",
                            "》",
                            "，",
                            "这",
                            "源自",
                            "萧红",
                            "写给",
                            "萧军信",
                            "中",
                            "的",
                            "一",
                            "句",
                            "话",
                            "：",
                            "“",
                            "这",
                            "不",
                            "正",
                            "是",
                            "我",
                            "的",
                            "黄金",
                            "时代",
                            "吗",
                            "？",
                            "”"
                        ]
                    }
            ];

            return mockData;
        }
    }
})();